# Generated by Django 4.2.13 on 2026-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("retail_price", models.DecimalField(decimal_places=5, max_digits=8)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state"], name="routes_fuel_state_172b38_idx"),
                    models.Index(
                        fields=["retail_price"], name="routes_fuel_retail__88f3a7_idx"
                    ),
                ],
            },
        ),
    ]
